# Generated by Django 5.1.4 on 2024-12-25 07:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AwardsList',
            fields=[
                ('award_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('award_Name', models.CharField(max_length=50)),
                ('award_Desc', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Builds',
            fields=[
                ('ea_build', models.IntegerField(primary_key=True, serialize=False)),
                ('build', models.CharField(max_length=25)),
                ('buildShort', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='PlayerList',
            fields=[
                ('ea_player_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Positions',
            fields=[
                ('ea_pos', models.IntegerField(primary_key=True, serialize=False)),
                ('position', models.CharField(max_length=20)),
                ('positionShort', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Seasons',
            fields=[
                ('season_ID', models.AutoField(primary_key=True, serialize=False)),
                ('season_text', models.CharField(max_length=50)),
                ('isPlayoff', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='TeamList',
            fields=[
                ('ea_club_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('club_full_name', models.CharField(max_length=50)),
                ('club_abbr', models.CharField(max_length=3)),
                ('club_location', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Games',
            fields=[
                ('game_ID', models.AutoField(primary_key=True, serialize=False)),
                ('game_length', models.PositiveIntegerField()),
                ('season_ID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='GHLWebsiteApp.seasons')),
            ],
        ),
        migrations.CreateModel(
            name='Awards',
            fields=[
                ('award_ID', models.AutoField(primary_key=True, serialize=False)),
                ('award_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GHLWebsiteApp.awardslist')),
                ('ea_player_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GHLWebsiteApp.playerlist')),
                ('season_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GHLWebsiteApp.seasons')),
            ],
        ),
        migrations.CreateModel(
            name='SkaterRecords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goals', models.PositiveSmallIntegerField()),
                ('assists', models.PositiveSmallIntegerField()),
                ('hits', models.PositiveSmallIntegerField()),
                ('plus_minus', models.SmallIntegerField()),
                ('sog', models.PositiveSmallIntegerField()),
                ('shot_attempts', models.PositiveSmallIntegerField()),
                ('deflections', models.PositiveSmallIntegerField()),
                ('ppg', models.PositiveSmallIntegerField()),
                ('shg', models.PositiveSmallIntegerField()),
                ('pass_att', models.PositiveSmallIntegerField()),
                ('pass_comp', models.PositiveSmallIntegerField()),
                ('saucer_pass', models.PositiveSmallIntegerField()),
                ('blocked_shots', models.PositiveSmallIntegerField()),
                ('takeaways', models.PositiveSmallIntegerField()),
                ('interceptions', models.PositiveSmallIntegerField()),
                ('giveaways', models.PositiveSmallIntegerField()),
                ('pens_drawn', models.PositiveSmallIntegerField()),
                ('pims', models.PositiveSmallIntegerField()),
                ('pk_clears', models.PositiveSmallIntegerField()),
                ('poss_time', models.PositiveSmallIntegerField()),
                ('fow', models.PositiveSmallIntegerField()),
                ('fol', models.PositiveSmallIntegerField()),
                ('build', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GHLWebsiteApp.builds')),
                ('ea_player_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GHLWebsiteApp.playerlist')),
                ('game_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GHLWebsiteApp.games')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GHLWebsiteApp.positions')),
                ('ea_club_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GHLWebsiteApp.teamlist')),
            ],
        ),
        migrations.AddField(
            model_name='playerlist',
            name='current_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='GHLWebsiteApp.teamlist'),
        ),
        migrations.CreateModel(
            name='GoalieRecords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shots_against', models.PositiveSmallIntegerField()),
                ('saves', models.PositiveSmallIntegerField()),
                ('breakaway_shots', models.PositiveSmallIntegerField()),
                ('breakaway_saves', models.PositiveSmallIntegerField()),
                ('ps_shots', models.PositiveSmallIntegerField()),
                ('ps_saves', models.PositiveSmallIntegerField()),
                ('game_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GHLWebsiteApp.games')),
                ('ea_player_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GHLWebsiteApp.playerlist')),
                ('ea_club_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GHLWebsiteApp.teamlist')),
            ],
        ),
        migrations.CreateModel(
            name='TeamRecords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_away', models.BooleanField()),
                ('goals_for', models.PositiveSmallIntegerField()),
                ('goals_against', models.PositiveSmallIntegerField()),
                ('pass_att_team', models.PositiveSmallIntegerField()),
                ('pass_comp_team', models.PositiveSmallIntegerField()),
                ('ppg_team', models.PositiveSmallIntegerField()),
                ('ppo_team', models.PositiveSmallIntegerField()),
                ('sog_team', models.PositiveSmallIntegerField()),
                ('toa_team', models.PositiveSmallIntegerField()),
                ('dnf', models.BooleanField()),
                ('fow_team', models.PositiveSmallIntegerField()),
                ('fol_team', models.PositiveSmallIntegerField()),
                ('hits_team', models.PositiveSmallIntegerField()),
                ('pims_team', models.PositiveSmallIntegerField()),
                ('shg_team', models.PositiveSmallIntegerField()),
                ('shot_att_team', models.PositiveSmallIntegerField()),
                ('ea_club_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GHLWebsiteApp.teamlist')),
                ('game_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GHLWebsiteApp.games')),
            ],
        ),
    ]
