# Generated by Django 5.1.4 on 2024-12-25 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GHLWebsiteApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamlist',
            name='team_logo_link',
            field=models.TextField(blank=True, null=True),
        ),
    ]
