# Generated by Django 5.1.4 on 2024-12-28 01:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GHLWebsiteApp', '0003_rename_award_id_awards_award_num_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='games',
            name='a_team_gf',
            field=models.IntegerField(blank=True, default='0', verbose_name='Away Score'),
        ),
        migrations.AddField(
            model_name='games',
            name='a_team_num',
            field=models.IntegerField(default='0', verbose_name='Away Team'),
        ),
        migrations.AddField(
            model_name='games',
            name='dnf',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='DNF'),
        ),
        migrations.AddField(
            model_name='games',
            name='expected_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Expected Game Time'),
        ),
        migrations.AddField(
            model_name='games',
            name='h_team_gf',
            field=models.IntegerField(blank=True, default='0', verbose_name='Home Score'),
        ),
        migrations.AddField(
            model_name='games',
            name='h_team_num',
            field=models.IntegerField(default='0', verbose_name='Home Team'),
        ),
        migrations.AddField(
            model_name='games',
            name='played_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Actual Game Time'),
        ),
        migrations.AddField(
            model_name='goalierecords',
            name='shutout',
            field=models.BooleanField(default='0'),
        ),
        migrations.AlterField(
            model_name='games',
            name='game_length',
            field=models.PositiveIntegerField(blank=True, default='3600', null=True, verbose_name='Game Length in seconds'),
        ),
        migrations.AlterField(
            model_name='games',
            name='season_num',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GHLWebsiteApp.seasons'),
        ),
        migrations.AlterField(
            model_name='seasons',
            name='isPlayoff',
            field=models.BooleanField(default=0),
        ),
    ]
