# Generated by Django 5.1.4 on 2024-12-28 20:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GHLWebsiteApp', '0004_games_a_team_gf_games_a_team_num_games_dnf_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='games',
            name='a_team_num',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='a_team', to='GHLWebsiteApp.teamlist'),
        ),
        migrations.AlterField(
            model_name='games',
            name='h_team_num',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='h_team', to='GHLWebsiteApp.teamlist'),
        ),
    ]
