# Generated by Django 5.1.4 on 2024-12-29 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GHLWebsiteApp', '0006_skaterrecords_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='games',
            name='a_team_points',
            field=models.PositiveSmallIntegerField(default='0', verbose_name="Away Team's Standings Points"),
        ),
        migrations.AddField(
            model_name='games',
            name='h_team_points',
            field=models.PositiveSmallIntegerField(default='0', verbose_name="Home Team's Standings Points"),
        ),
    ]
