# Generated by Django 5.1.4 on 2024-12-30 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GHLWebsiteApp', '0009_rename_game_length_games_gamelength_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='goalierecords',
            name='win',
            field=models.BooleanField(default='0'),
        ),
    ]
