# Generated by Django 5.1.4 on 2024-12-30 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GHLWebsiteApp', '0010_goalierecords_win'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Seasons',
            new_name='Season',
        ),
    ]
