# Generated by Django 5.1.4 on 2024-12-30 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GHLWebsiteApp', '0011_rename_seasons_season'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Awards',
            new_name='AwardAssign',
        ),
        migrations.RenameModel(
            old_name='AwardsList',
            new_name='AwardTitle',
        ),
        migrations.RenameModel(
            old_name='Builds',
            new_name='Build',
        ),
        migrations.RenameModel(
            old_name='Games',
            new_name='Game',
        ),
        migrations.RenameModel(
            old_name='GoalieRecords',
            new_name='GoalieRecord',
        ),
        migrations.RenameModel(
            old_name='PlayerList',
            new_name='Player',
        ),
        migrations.RenameModel(
            old_name='Positions',
            new_name='Position',
        ),
        migrations.RenameModel(
            old_name='SkaterRecords',
            new_name='SkaterRecord',
        ),
        migrations.RenameModel(
            old_name='TeamList',
            new_name='Team',
        ),
        migrations.RenameModel(
            old_name='TeamRecords',
            new_name='TeamRecord',
        ),
    ]
