# Generated by Django 5.1.4 on 2025-01-03 04:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GHLWebsiteApp', '0013_goalierecord_loss_goalierecord_otloss'),
    ]

    operations = [
        migrations.CreateModel(
            name='Standing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wins', models.IntegerField(default=0)),
                ('losses', models.IntegerField(default=0)),
                ('otlosses', models.IntegerField(default=0)),
                ('points', models.IntegerField(default=0)),
                ('goalsfor', models.IntegerField(default=0)),
                ('goalsagainst', models.IntegerField(default=0)),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GHLWebsiteApp.season')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GHLWebsiteApp.team')),
            ],
            options={
                'ordering': ['-points', '-wins', '-goalsfor', 'goalsagainst'],
            },
        ),
    ]
