# Generated by Django 5.1.4 on 2025-01-03 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GHLWebsiteApp', '0014_standing'),
    ]

    operations = [
        migrations.AddField(
            model_name='standing',
            name='gp',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='standing',
            name='lastten',
            field=models.CharField(default='n/a', max_length=8),
        ),
        migrations.AddField(
            model_name='standing',
            name='pkperc',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=3),
        ),
        migrations.AddField(
            model_name='standing',
            name='ppperc',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=3),
        ),
        migrations.AddField(
            model_name='standing',
            name='streak',
            field=models.CharField(default='n/a', max_length=4),
        ),
        migrations.AddField(
            model_name='standing',
            name='winperc',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=3),
        ),
    ]
