# Generated by Django 5.1.4 on 2025-01-03 22:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GHLWebsiteApp', '0015_standing_gp_standing_lastten_standing_pkperc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='primarypos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='primary', to='GHLWebsiteApp.position'),
        ),
        migrations.AddField(
            model_name='player',
            name='secondarypos',
            field=models.ManyToManyField(blank=True, null=True, related_name='secondary', to='GHLWebsiteApp.position'),
        ),
    ]
