# Generated by Django 5.1.4 on 2025-01-03 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GHLWebsiteApp', '0017_alter_player_secondarypos'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='playerpic',
            field=models.TextField(blank=True, null=True),
        ),
    ]
