# Generated by Django 5.1.4 on 2025-01-09 02:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GHLWebsiteApp', '0019_leader'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='standing',
            options={'ordering': ['-points', '-wins', '-goalsfor', 'goalsagainst', 'team__club_full_name']},
        ),
        migrations.AlterField(
            model_name='leader',
            name='player',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='GHLWebsiteApp.player'),
        ),
    ]
