# Generated by Django 5.1.4 on 2025-01-09 02:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GHLWebsiteApp', '0020_alter_standing_options_alter_leader_player'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leader',
            name='player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='GHLWebsiteApp.player'),
        ),
    ]
