# Generated by Django 5.1.4 on 2025-01-17 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GHLWebsiteApp', '0021_alter_leader_player'),
    ]

    operations = [
        migrations.AddField(
            model_name='skaterrecord',
            name='pass_pct',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
        migrations.AddField(
            model_name='skaterrecord',
            name='shot_eff',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
        migrations.AddField(
            model_name='skaterrecord',
            name='shot_pct',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
    ]
