# Generated by Django 5.1.4 on 2025-01-17 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GHLWebsiteApp', '0024_alter_goalierecord_save_pct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skaterrecord',
            name='pass_pct',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='skaterrecord',
            name='shot_eff',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='skaterrecord',
            name='shot_pct',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
