# Generated by Django 5.1.4 on 2025-01-21 01:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GHLWebsiteApp', '0025_alter_skaterrecord_pass_pct_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AwardVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('votes_num', models.SmallIntegerField(default=0)),
                ('award_num', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GHLWebsiteApp.awardtitle')),
                ('ea_player_num', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GHLWebsiteApp.player')),
                ('season_num', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GHLWebsiteApp.season')),
            ],
        ),
    ]
