# Generated by Django 5.1.4 on 2025-04-15 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GHLWebsiteApp', '0027_alter_goalierecord_breakaway_saves_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='awardassign',
            name='place',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(3, '3rd'), (2, '2nd'), (1, '1st')], default=1, null=True),
        ),
    ]
