# Generated by Django 5.1.4 on 2025-04-16 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GHLWebsiteApp', '0028_awardassign_place'),
    ]

    operations = [
        migrations.RenameField(
            model_name='awardvote',
            old_name='award_num',
            new_name='award_type',
        ),
        migrations.RemoveField(
            model_name='awardassign',
            name='ea_player_num',
        ),
        migrations.RemoveField(
            model_name='awardassign',
            name='place',
        ),
        migrations.AddField(
            model_name='awardassign',
            name='players',
            field=models.ManyToManyField(blank=True, to='GHLWebsiteApp.player'),
        ),
        migrations.AddField(
            model_name='awardtitle',
            name='assign_or_vote',
            field=models.BooleanField(default=False, help_text='True = Assign, False = Vote', verbose_name='Assign/Vote'),
        ),
        migrations.AddField(
            model_name='season',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Start Date'),
        ),
        migrations.AlterField(
            model_name='awardtitle',
            name='award_Desc',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='awardtitle',
            name='award_Name',
            field=models.CharField(max_length=50, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='season',
            name='isPlayoff',
            field=models.BooleanField(default=False, help_text='True = Playoffs, False = Regular Season', verbose_name='Playoffs?'),
        ),
        migrations.AlterField(
            model_name='season',
            name='season_num',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Autonum'),
        ),
        migrations.AlterField(
            model_name='season',
            name='season_text',
            field=models.CharField(max_length=50, verbose_name='Season Name'),
        ),
    ]
