# Generated by Django 5.1.4 on 2025-06-08 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GHLWebsiteApp', '0030_awardassign_team_awardvote_team_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='season',
            name='isPlayoff',
        ),
        migrations.AddField(
            model_name='season',
            name='isActive',
            field=models.BooleanField(default=True, help_text='Only one season can be active at a time', verbose_name='Is Active Season'),
        ),
        migrations.AddField(
            model_name='season',
            name='season_type',
            field=models.CharField(choices=[('preseason', 'Preseason'), ('regular', 'Regular Season'), ('playoffs', 'Playoffs')], default='preseason', help_text='Preseason, Regular Season, or Playoffs', max_length=20, verbose_name='Season Type'),
        ),
        migrations.AddConstraint(
            model_name='season',
            constraint=models.UniqueConstraint(condition=models.Q(('isActive', True)), fields=('isActive',), name='unique_active_season', violation_error_message='There can only be one active season at a time.'),
        ),
    ]
