# Generated by Django 5.1.4 on 2025-06-08 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GHLWebsiteApp', '0031_remove_season_isplayoff_season_isactive_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='season',
            constraint=models.UniqueConstraint(condition=models.Q(('isActive', True)), fields=('isActive',), name='unique_active_season', violation_error_message='There can only be one active season at a time.'),
        ),
    ]
