# Generated by Django 5.1.4 on 2025-06-08 23:21

import django.db.models.functions.text
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GHLWebsiteApp', '0032_season_unique_active_season'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='player',
            options={'ordering': [django.db.models.functions.text.Lower('username')]},
        ),
        migrations.AlterModelOptions(
            name='team',
            options={'ordering': [django.db.models.functions.text.Lower('club_full_name')]},
        ),
    ]
