# Generated by Django 5.1.4 on 2025-06-10 06:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GHLWebsiteApp', '0033_alter_player_options_alter_team_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayoffSeries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_num', models.PositiveIntegerField(verbose_name='Round Number')),
                ('low_seed_num', models.PositiveSmallIntegerField(default=0, help_text='1 for lowest seed, 2 for second lowest, etc.', verbose_name='Low Seed Number')),
                ('high_seed_num', models.PositiveSmallIntegerField(default=0, help_text='8 for highest seed, 7 for second highest, etc.', verbose_name='High Seed Number')),
                ('low_seed_wins', models.PositiveSmallIntegerField(default=0, verbose_name='Low Seed Wins')),
                ('high_seed_wins', models.PositiveSmallIntegerField(default=0, verbose_name='High Seed Wins')),
                ('high_seed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='high_seed_series', to='GHLWebsiteApp.team', verbose_name='High Seed')),
                ('low_seed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='low_seed_series', to='GHLWebsiteApp.team', verbose_name='Low Seed')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GHLWebsiteApp.season', verbose_name='Season')),
                ('series_winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='series_winner', to='GHLWebsiteApp.team', verbose_name='Series Winner')),
            ],
        ),
    ]
