# Generated by Django 5.1.4 on 2025-06-10 06:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GHLWebsiteApp', '0034_playoffseries'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayoffRound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_num', models.PositiveSmallIntegerField(verbose_name='Round Number')),
                ('round_name', models.CharField(help_text='Name of the playoff round (e.g., Quarterfinals, Semifinals, Finals)', max_length=50, verbose_name='Round Name')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GHLWebsiteApp.season', verbose_name='Season')),
            ],
        ),
        migrations.AlterField(
            model_name='playoffseries',
            name='round_num',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='series_in_round', to='GHLWebsiteApp.playoffround', verbose_name='Round Number'),
        ),
    ]
