# Generated by Django 5.1.4 on 2025-06-24 06:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GHLWebsiteApp', '0035_playoffround_alter_playoffseries_round_num'),
    ]

    operations = [
            migrations.RemoveField(
            model_name='team',
            name='club_location',
        ),
        migrations.AddField(
            model_name='team',
            name='team_color',
            field=models.CharField(default='#000000', help_text="Hex color code for the team's primary color", max_length=7, verbose_name='Team Color'),
        ),
        migrations.AlterField(
            model_name='game',
            name='a_team_num',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='a_team', to='GHLWebsiteApp.team', verbose_name='Away Team'),
        ),
        migrations.AlterField(
            model_name='game',
            name='h_team_num',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='h_team', to='GHLWebsiteApp.team', verbose_name='Home Team'),
        ),
        migrations.AlterField(
            model_name='team',
            name='club_abbr',
            field=models.CharField(help_text='3-letter abbreviation for the club', max_length=3, verbose_name='Club Abbreviation'),
        ),
        migrations.AlterField(
            model_name='team',
            name='club_full_name',
            field=models.CharField(max_length=50, verbose_name='Full Club Name'),
        ),
        migrations.AlterField(
            model_name='team',
            name='ea_club_num',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='EA Club Number'),
        ),
        migrations.AlterField(
            model_name='team',
            name='isActive',
            field=models.BooleanField(default=True, help_text='Indicates if the team is currently active in the league', verbose_name='Is Active Team'),
        ),
        migrations.AlterField(
            model_name='team',
            name='team_logo_link',
            field=models.TextField(blank=True, help_text='Link to the team logo image', null=True, verbose_name='Team Logo Link'),
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('schedule_num', models.AutoField(primary_key=True, serialize=False)),
                ('games_per_matchup', models.PositiveIntegerField(default=8, verbose_name='Home Games per Matchup')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Start Date')),
                ('season_num', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GHLWebsiteApp.season', verbose_name='Season')),
            ],
        ),
    ]
