# Generated by Django 5.1.4 on 2025-06-24 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GHLWebsiteApp', '0036_remove_team_club_location_team_team_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='team_code',
            field=models.CharField(blank=True, help_text='GHL specific matchup code to be used in EA NHL games', max_length=6, null=True, verbose_name='Game Matchup Code'),
        ),
    ]
