# Generated by Django 5.1.4 on 2025-06-25 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GHLWebsiteApp', '0037_team_team_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='standing',
            name='playoffs',
            field=models.CharField(choices=[('x', 'Clinched Playoff Spot'), ('y', 'Clinched Division'), ('z', 'Clinched Conference'), ('p', "President's Trophy"), ('', 'No Status')], default='', help_text='Indicates playoff status of the team', max_length=1, verbose_name='Playoff Status'),
        ),
    ]
