# Generated by Django 5.1.4 on 2025-07-03 08:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GHLWebsiteApp', '0039_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='player_link',
            field=models.OneToOneField(blank=True, help_text="Link to the player's profile in the GHL database", null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='GHLWebsiteApp.player', verbose_name='Link to your player stats'),
        ),
    ]
