# Generated by Django 5.1.4 on 2025-07-03 09:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GHLWebsiteApp', '0040_user_player_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannedUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(help_text='Reason why the user was banned', verbose_name='Reason for Ban')),
                ('ban_date', models.DateTimeField(auto_now_add=True, help_text='Date and time when the user was banned', verbose_name='Ban Date')),
                ('ban_duration', models.DurationField(blank=True, default=None, help_text="Duration of the ban. Use '0' for permanent bans.", null=True, verbose_name='Ban Duration')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Banned User')),
            ],
        ),
    ]
