# Generated by Django 5.1.4 on 2025-07-03 09:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GHLWebsiteApp', '0041_banneduser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banneduser',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='GHLWebsiteApp.player', verbose_name='Banned User'),
        ),
    ]
