# Generated by Django 5.1.4 on 2025-07-06 02:49

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GHLWebsiteApp', '0043_alter_user_player_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(help_text='Content of the announcement', verbose_name='Announcement Content')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when the announcement was created', verbose_name='Created At')),
                ('author', models.ForeignKey(default=django.utils.timezone.now, help_text='User who created the announcement', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Author')),
            ],
        ),
    ]
