# Generated by Django 5.1.4 on 2025-07-06 05:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GHLWebsiteApp', '0044_announcement'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='jersey_num',
            field=models.PositiveSmallIntegerField(blank=True, default=99, null=True, verbose_name='Jersey Number'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='author',
            field=models.ForeignKey(blank=True, help_text='User who created the announcement', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Author'),
        ),
    ]
