# Generated by Django 5.1.4 on 2025-07-16 22:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GHLWebsiteApp', '0047_playeravailability'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkaterWAR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gar_offence', models.DecimalField(decimal_places=2, max_digits=6)),
                ('gar_defence', models.DecimalField(decimal_places=2, max_digits=6)),
                ('gar_turnover', models.DecimalField(decimal_places=2, max_digits=6)),
                ('gar_penalties', models.DecimalField(decimal_places=2, max_digits=6)),
                ('gar_faceoffs', models.DecimalField(decimal_places=2, max_digits=6)),
                ('gar_total', models.DecimalField(decimal_places=2, max_digits=7)),
                ('war', models.DecimalField(decimal_places=2, max_digits=6)),
                ('gar_offence_pct', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('gar_defence_pct', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('gar_turnover_pct', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('gar_penalties_pct', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('gar_faceoffs_pct', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('war_percentile', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('weights_version', models.CharField(default='v1', max_length=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GHLWebsiteApp.player')),
                ('position', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='GHLWebsiteApp.position')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GHLWebsiteApp.season')),
            ],
            options={
                'ordering': ['-war'],
                'unique_together': {('player', 'season', 'weights_version')},
            },
        ),
    ]
