# Generated by Django 5.1.4 on 2025-07-17 03:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GHLWebsiteApp', '0048_skaterwar'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='skaterwar',
            unique_together={('player', 'season', 'position', 'weights_version')},
        ),
    ]
