# Generated by Django 5.1.4 on 2025-07-17 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GHLWebsiteApp', '0049_alter_skaterwar_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='skaterwar',
            name='games_played',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
