# Generated by Django 5.1.4 on 2025-07-18 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GHLWebsiteApp', '0050_skaterwar_games_played'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='team_location',
            field=models.CharField(default='Location', help_text="Location of the team, e.g., 'New York', 'Toronto'", max_length=50, verbose_name='Team Location'),
        ),
        migrations.AddField(
            model_name='team',
            name='team_name',
            field=models.CharField(default='Name', help_text="Name of the team, e.g., 'Rangers', 'Maple Leafs'", max_length=50, verbose_name='Team Name'),
        ),
    ]
