# Generated by Django 5.1.4 on 2025-07-20 00:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GHLWebsiteApp', '0051_team_team_location_team_team_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamNeed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(choices=[('any', 'Any'), ('key', 'Key'), ('core', 'Core'), ('depth', 'Depth'), ('prospect', 'Prospect'), ('avail', 'Schedule Availability'), ('cap', 'Cap Space')], default='any', max_length=10, verbose_name='Need Type')),
                ('note', models.CharField(blank=True, help_text="E.g. 'Top-4 LD', 'Faceoff specialist', etc.", max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('position', models.ManyToManyField(blank=True, null=True, to='GHLWebsiteApp.position', verbose_name='Position Needed')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GHLWebsiteApp.team')),
            ],
        ),
        migrations.CreateModel(
            name='TradeBlockPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listed_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, help_text='Optional notes about the trade value or desired return')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GHLWebsiteApp.player')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GHLWebsiteApp.team')),
            ],
        ),
    ]
