# Generated by Django 5.1.4 on 2025-07-20 09:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GHLWebsiteApp', '0052_teamneed_tradeblockplayer'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='manager',
            field=models.OneToOneField(blank=True, help_text='User who manages the team in the GHL', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Team Manager'),
        ),
    ]
