# Generated by Django 5.1.4 on 2025-07-25 00:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GHLWebsiteApp', '0053_team_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamneed',
            name='position',
            field=models.ManyToManyField(blank=True, to='GHLWebsiteApp.position', verbose_name='Position Needed'),
        ),
        migrations.CreateModel(
            name='SkaterRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('games_played', models.PositiveSmallIntegerField(default=0)),
                ('off_rat', models.DecimalField(decimal_places=2, max_digits=6)),
                ('def_rat', models.DecimalField(decimal_places=2, max_digits=6)),
                ('team_rat', models.DecimalField(decimal_places=2, max_digits=6)),
                ('ovr_rat', models.DecimalField(decimal_places=2, max_digits=6)),
                ('off_pct', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('def_pct', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('team_pct', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('ovr_pct', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('weights_version', models.CharField(default='v1', max_length=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GHLWebsiteApp.player')),
                ('position', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='GHLWebsiteApp.position')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GHLWebsiteApp.season')),
            ],
            options={
                'ordering': ['-ovr_pct', 'player__username'],
                'unique_together': {('player', 'season', 'position', 'weights_version')},
            },
        ),
        migrations.DeleteModel(
            name='SkaterWAR',
        ),
    ]
