# Generated by Django 5.1.4 on 2025-07-25 02:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GHLWebsiteApp', '0054_alter_teamneed_position_skaterrating_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameSkaterRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offense_rating', models.DecimalField(decimal_places=2, max_digits=6)),
                ('defense_rating', models.DecimalField(decimal_places=2, max_digits=6)),
                ('teamplay_rating', models.DecimalField(decimal_places=2, max_digits=6)),
                ('game_result_bonus', models.DecimalField(decimal_places=2, max_digits=5)),
                ('overall_rating', models.DecimalField(decimal_places=2, max_digits=6)),
                ('calculated_at', models.DateTimeField(auto_now_add=True)),
                ('skater_record', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='GHLWebsiteApp.skaterrecord')),
            ],
            options={
                'unique_together': {('skater_record',)},
            },
        ),
    ]
