# Generated by Django 5.1.4 on 2025-07-25 09:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GHLWebsiteApp', '0055_gameskaterrating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameskaterrating',
            name='skater_record',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gameskaterrating', to='GHLWebsiteApp.skaterrecord'),
        ),
    ]
