# Generated by Django 5.1.4 on 2025-08-13 08:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GHLWebsiteApp', '0056_alter_gameskaterrating_skater_record'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameGoalieRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goalie_rating', models.DecimalField(decimal_places=2, max_digits=6)),
                ('teamplay_rating', models.DecimalField(decimal_places=2, max_digits=6)),
                ('game_result_bonus', models.DecimalField(decimal_places=2, max_digits=6)),
                ('overall_rating', models.DecimalField(decimal_places=2, max_digits=6)),
                ('calculated_at', models.DateTimeField(auto_now_add=True)),
                ('goalie_record', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gamegoalierating', to='GHLWebsiteApp.goalierecord')),
            ],
            options={
                'unique_together': {('goalie_record',)},
            },
        ),
        migrations.CreateModel(
            name='GoalieRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('games_played', models.PositiveSmallIntegerField(default=0)),
                ('gk_rat', models.DecimalField(decimal_places=2, max_digits=6)),
                ('team_rat', models.DecimalField(decimal_places=2, max_digits=6)),
                ('ovr_rat', models.DecimalField(decimal_places=2, max_digits=6)),
                ('gk_pct', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('team_pct', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('ovr_pct', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('weights_version', models.CharField(default='v1', max_length=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GHLWebsiteApp.player')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GHLWebsiteApp.season')),
            ],
            options={
                'ordering': ['-gk_pct', 'player__username'],
                'unique_together': {('player', 'season', 'weights_version')},
            },
        ),
    ]
