# Generated by Django 5.1.4 on 2025-08-22 04:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GHLWebsiteApp', '0057_gamegoalierating_goalierating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playoffseries',
            name='high_seed',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='high_seed_series', to='GHLWebsiteApp.team', verbose_name='High Seed'),
        ),
        migrations.AlterField(
            model_name='playoffseries',
            name='high_seed_num',
            field=models.PositiveSmallIntegerField(blank=True, default=0, help_text='8 for highest seed, 7 for second highest, etc.', null=True, verbose_name='High Seed Number'),
        ),
    ]
