# Generated by Django 5.1.4 on 2025-08-22 05:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GHLWebsiteApp', '0058_alter_playoffseries_high_seed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playoffseries',
            name='low_seed',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='low_seed_series', to='GHLWebsiteApp.team', verbose_name='Low Seed'),
        ),
        migrations.AlterField(
            model_name='playoffseries',
            name='low_seed_num',
            field=models.PositiveSmallIntegerField(blank=True, default=0, help_text='1 for lowest seed, 2 for second lowest, etc.', null=True, verbose_name='Low Seed Number'),
        ),
    ]
