# Generated by Django 5.1.4 on 2025-11-02 11:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GHLWebsiteApp', '0059_alter_playoffseries_low_seed_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scheduling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GHLWebsiteApp.game')),
                ('player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='GHLWebsiteApp.player')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GHLWebsiteApp.position')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GHLWebsiteApp.team')),
            ],
            options={
                'unique_together': {('game', 'team', 'position')},
            },
        ),
    ]
