# Generated by Django 5.1.4 on 2025-11-02 11:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GHLWebsiteApp', '0060_scheduling'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='ass_manager',
            field=models.OneToOneField(blank=True, help_text='User who is the assistant manager for the team in the GHL', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_assistant_manager', to=settings.AUTH_USER_MODEL, verbose_name='Team Assistant Manager'),
        ),
        migrations.AlterField(
            model_name='team',
            name='manager',
            field=models.OneToOneField(blank=True, help_text='User who manages the team in the GHL', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_manager', to=settings.AUTH_USER_MODEL, verbose_name='Team Manager'),
        ),
    ]
