# Generated by Django 5.1.4 on 2025-11-05 23:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GHLWebsiteApp', '0061_team_ass_manager_alter_team_manager'),
    ]

    operations = [
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GHLWebsiteApp.player')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GHLWebsiteApp.season')),
            ],
            options={
                'unique_together': {('player', 'season')},
            },
        ),
    ]
