# Generated by Django 5.1.4 on 2025-11-07 00:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GHLWebsiteApp', '0062_salary'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamServerBinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guild_id', models.BigIntegerField(help_text='The Discord server (guild) ID', unique=True, verbose_name='Discord Guild ID')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='GHLWebsiteApp.team')),
            ],
        ),
    ]
