# Generated by Django 5.1.4 on 2025-11-07 02:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GHLWebsiteApp', '0063_teamserverbinding'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingServerBinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guild_id', models.BigIntegerField(unique=True)),
                ('requested_by', models.BigIntegerField()),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('requested_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GHLWebsiteApp.team')),
            ],
        ),
    ]
