# Generated by Django 5.1.4 on 2025-11-19 06:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GHLWebsiteApp', '0064_pendingserverbinding'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayoffConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playoff_teams', models.PositiveSmallIntegerField(default=8, help_text='Total number of teams that qualify for playoffs from this season.')),
                ('season', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='playoff_config', to='GHLWebsiteApp.season')),
            ],
        ),
    ]
