# Generated by Django 5.1.4 on 2025-11-19 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GHLWebsiteApp', '0065_playoffconfig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='standing',
            name='playoffs',
            field=models.CharField(blank=True, choices=[('x', 'Clinched Playoff Spot'), ('y', 'Clinched Division'), ('z', 'Clinched Conference'), ('p', "President's Trophy"), ('', 'No Status')], default='', help_text='Indicates playoff status of the team', max_length=1, verbose_name='Playoff Status'),
        ),
    ]
