# Generated by Django 5.1.4 on 2025-11-22 18:51

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GHLWebsiteApp', '0066_alter_standing_playoffs'),
    ]

    operations = [
        migrations.AddField(
            model_name='season',
            name='signups_open',
            field=models.BooleanField(default=False, help_text='If true, players can submit signups for this season.', verbose_name='Signups Open'),
        ),
        migrations.CreateModel(
            name='Signup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days_per_week', models.PositiveSmallIntegerField(help_text='How many nights per week the player can commit (2–5).', validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(5)], verbose_name='Nights per Week')),
                ('scheduling_issues', models.TextField(blank=True, help_text='Holidays, work constraints, etc.', verbose_name='Scheduling Issues')),
                ('invited_by_name', models.CharField(blank=True, help_text='Who invited them to the league (username or friend).', max_length=50, verbose_name='Invited By')),
                ('committed_to_league', models.BooleanField(default=True, help_text='True if they intend to prioritize this league.', verbose_name='Committed to GHL')),
                ('other_league_obligations', models.TextField(blank=True, help_text='Any existing leagues/teams they also play with.', verbose_name='Other League Obligations')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('player', models.ForeignKey(blank=True, help_text='If linked, ties signup directly to a Player record.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='GHLWebsiteApp.player', verbose_name='Linked Player (optional)')),
                ('primary_position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signup_primary', to='GHLWebsiteApp.position', verbose_name='Primary Position')),
                ('season', models.ForeignKey(help_text='Season this signup applies to.', on_delete=django.db.models.deletion.CASCADE, to='GHLWebsiteApp.season', verbose_name='Season')),
                ('secondary_positions', models.ManyToManyField(blank=True, help_text='Should include the primary position as well.', related_name='signup_secondary', to='GHLWebsiteApp.position', verbose_name='Secondary Positions')),
                ('user', models.ForeignKey(help_text='Account used to submit the signup.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Website User')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('season', 'user')},
            },
        ),
    ]
