# Generated by Django 5.1.4 on 2025-11-24 13:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GHLWebsiteApp', '0067_season_signups_open_signup'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyThreeStars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start', models.DateField()),
                ('blurb', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('first_star', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='three_star_first', to='GHLWebsiteApp.player')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GHLWebsiteApp.season')),
                ('second_star', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='three_star_second', to='GHLWebsiteApp.player')),
                ('third_star', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='three_star_third', to='GHLWebsiteApp.player')),
            ],
            options={
                'unique_together': {('season', 'week_start')},
            },
        ),
    ]
