# Generated by Django 5.1.4 on 2025-11-29 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GHLWebsiteApp', '0068_weeklythreestars'),
    ]

    operations = [
        migrations.CreateModel(
            name='TwitchStreamer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, unique=True)),
                ('user_id', models.CharField(max_length=100)),
                ('subscribed', models.BooleanField(default=True)),
            ],
        ),
    ]
