# Generated by Django 5.1.4 on 2025-11-30 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GHLWebsiteApp', '0069_twitchstreamer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chirp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text="Use {mention} where the target's Discord mention should go.")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
