# Generated by Django 5.1.4 on 2024-12-29 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GHLWebsiteApp', '0005_alter_games_a_team_num_alter_games_h_team_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='skaterrecords',
            name='points',
            field=models.PositiveSmallIntegerField(default='0'),
        ),
    ]
