# Generated by Django 5.1.4 on 2024-12-30 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GHLWebsiteApp', '0008_remove_games_a_team_points_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='games',
            old_name='game_length',
            new_name='gamelength',
        ),
        migrations.AddField(
            model_name='teamlist',
            name='isActive',
            field=models.BooleanField(default=True),
        ),
    ]
