# Generated by Django 5.1.4 on 2025-01-04 03:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GHLWebsiteApp', '0018_player_playerpic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute', models.CharField(max_length=3)),
                ('stat', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GHLWebsiteApp.player')),
            ],
        ),
    ]
