# Generated by Django 5.1.4 on 2025-01-17 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GHLWebsiteApp', '0023_goalierecord_gaa_goalierecord_save_pct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goalierecord',
            name='save_pct',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
