from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name="index"),
    path('standings/', views.standings, name="standings"),
    path('leaders/', views.leaders, name="leaders"),
    path('skaters/', views.skaters, name="skaters"),
    path('skaters/<int:season>/', views.skaters, name="skaters_season"),
    path('skaters/advanced/', views.skatersAdvanced, name="skatersAdvanced"),
    path('skaters/advanced/<int:season>/', views.skatersAdvanced, name="skatersAdvanced_season"),
    path('goalies/', views.goalies, name="goalies"),
    path('goalies/<int:season>/', views.goalies, name="goalies_season"),
    path('team/<int:team>/', views.team, name="team"),
    path('team/<int:team>/seasonnum-<int:season>', views.team, name="team_season"),
    path('player/', views.skaters, name="playernonum"),
    path('player/<int:player>/', views.player, name="player"),
    path('playerlist/', views.playerlist, name="playerlist"),
    path('awards/', views.awardsDef, name="awardsDef"),
    path('awards/<int:awardnum>/', views.awards, name="awards"),
    path('draft/', views.draft, name="draft"),
    path('game/<int:game>/', views.game, name="game"),
    path('gameapi/', views.GamesRequest, name="gamesrequest"),
    path('uploadcsvforgames/', views.upload_file, name="upload_file"),
    path('glossary/', views.glossary, name="glossary"),
    path('export/team/<int:team_id>/', views.export_team, name="export_team"),
    path('export/playerdata/', views.export_player_data, name="export_player_data"),
    path('profile/', views.user_profile, name="user_profile"),
    path('profile/availability/', views.player_availability_view, name="player_availability"),
    path('register/', views.register, name='register'),
    path('api/player/<int:player_id>/', views.player_details, name='player-details'),
    path('media/weekly-stats/', views.weekly_stats_view, name='weekly_stats'),
    path('manageteam/', views.manager_view, name='manager_view'),
]